### ISSUE TITLE
기타 MVP 기능의 API 명세를 정의합니다. (공지 사항, 피드백 등)

### ISSUE THREAD

**Issue by cutehammond772** [SWM-Thlee/linked-paper#10]
## 작업 내용
- Swagger를 이용하여 기타 MVP 기능의 API 명세를 작성합니다.

## 작업 결과
- 공지 사항을 불러오는 API 명세 결과물
- 피드백 폼을 보내는 API 명세 결과물

**Comment by ljy2855** [comment]
#9 에서 같이 확인해 리뷰했습니다! :)
